import "swiper/css";
import "swiper/css/bundle";
import "swiper/css/mousewheel";
import "./index.scss";
import "./js/pages/home_page";
import "./js/pages/chat_page";
import "./js/pages/creating_adv_page";
import "./js/pages/adv-card";
import "./js/pages/adv-card-on-check";
import "./js/pages/adv-card-preview";
import "./js/pages/seller-card";
import "./js/pages/promotion_page";
import "./js/pages/characteristic";
import "./js/pages/filter";
import "./js/components/header";
import "./js/components/modal";
import "./js/components/forms";
import "./js/components/login-modal";
import "./js/components/signup-modal";
import "./js/components/options-modal";
import "./js/components/reset-password-modal";
import "./js/components/change-tel-modal";
import "./js/components/change-email-modal";
import "./js/components/change-password-modal";
import { example } from "./js/utils/constants";
console.log(example);
